package com.fossforbrokies.brokiecam.core.video

import android.media.MediaCodec
import android.media.MediaCodecInfo
import android.media.MediaFormat
import android.os.Build
import android.util.Log
import android.view.Surface
import androidx.annotation.RequiresApi
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.cancelAndJoin
import kotlinx.coroutines.channels.BufferOverflow
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch

private const val LOG_TAG = "H264Encoder"

/**
 * Hardware-accelerated H.264 Video Encoder.
 *
 * Captures raw frames from a [Surface] (provided by CameraX)
 * and outputs Annex-B formatted NAL units via [SharedFlow].
 *
 * @property width The target video width in pixels.
 * @property height The target video height in pixels.
 * @property frameRate The target frames per second (fps).
 * @property bitRate The target bitrate in bits per second (bps). Default is 4 Mbps.
 */
class H264Encoder(
    private val width: Int = 1280,
    private val height: Int = 720,
    private val frameRate: Int = 30,
    private val bitRate: Int = 4_000_000, // 4 Mbps stream
) {
    private var codec: MediaCodec? = null

    /**
     * The input surface generated by the MediaCodec.
     * CameraX draws to this surface for the encoder to receive frames.
     */
    var inputSurface: Surface? = null
        private set

    private var isEncoding = false
    private var encoderJob: Job? = null

    /** Backpressure-aware internal shared flow */
    private val _videoFrameFlow = MutableSharedFlow<ByteArray>(
        extraBufferCapacity = 60,
        onBufferOverflow = BufferOverflow.DROP_OLDEST
    )

    /** Public read-only stream of encoded H.264 NAL units. */
    val videoFrameFlow = _videoFrameFlow.asSharedFlow()

    /**
     * Configures and starts the hardware encoder, generating [inputSurface].
     * Launches a background coroutine to continuously drain encoded data.
     *
     * @param scope The coroutine scope used to launch the buffer-draining loop.
     */
    @RequiresApi(Build.VERSION_CODES.Q)
    fun start(scope: CoroutineScope){
        if (isEncoding) return

        try{

            // Encoder configurations
            val format = MediaFormat.createVideoFormat(MediaFormat.MIMETYPE_VIDEO_AVC, width, height).apply {
                setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface)
                setInteger(MediaFormat.KEY_BIT_RATE, bitRate)
                setInteger(MediaFormat.KEY_FRAME_RATE, frameRate)
                setInteger(MediaFormat.KEY_I_FRAME_INTERVAL, 1) // Keyframe every 1 second
                setInteger(MediaFormat.KEY_PREPEND_HEADER_TO_SYNC_FRAMES, 1) // Prepend SPS/PPS

            }

            // Set up encoder
            codec = MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_VIDEO_AVC).apply {
                configure(format, null, null, MediaCodec.CONFIGURE_FLAG_ENCODE)
                inputSurface = createInputSurface()
                start()
            }

            isEncoding = true

            // Spin up a dedicated loop to pull encoded frames from output buffers
            encoderJob = scope.launch(Dispatchers.IO){
                drainOutputLoop()
            }

        } catch (e: Exception) {
            Log.e(LOG_TAG, "Failed to start H.264 Encoder", e)
        }
    }

    /**
     * Continuously reads NAL units from [MediaCodec] and emits them to the flow
     */
    private suspend fun drainOutputLoop(){
        // Metadata for each encoded frame (size, offset, timestamp, flags)
        // dequeueOutputBuffer() dynamically overwrites those values in the loop
        val bufferInfo = MediaCodec.BufferInfo()
        val currentCodec = codec ?: return

        while (currentCoroutineContext().isActive && isEncoding){
            try{
                // Wait up to 10ms for a new buffer from internal buffer pool
                val outputBufferId = currentCodec.dequeueOutputBuffer(bufferInfo, 10000)

                if (outputBufferId >= 0){
                    val outputBuffer = currentCodec.getOutputBuffer(outputBufferId)

                    if (outputBuffer != null && bufferInfo.size > 0){
                        outputBuffer.position(bufferInfo.offset)
                        outputBuffer.limit(bufferInfo.offset + bufferInfo.size)

                        // Save to
                        val chunk = ByteArray(bufferInfo.size)
                        outputBuffer.get(chunk)

                        _videoFrameFlow.tryEmit(chunk)
                    }

                    // Release the buffer back to the hardware pool
                    currentCodec.releaseOutputBuffer(outputBufferId, false)
                }

            } catch (e: Exception) {
                Log.e(LOG_TAG, "Error draining encoder buffer", e)
                break
            }
        }
    }

    /**
     * Tears down the hardware encoder, releases the surface,
     * and cancels the draining coroutine
     */
    suspend fun stop(){
        if (!isEncoding) return

        isEncoding = false
        encoderJob?.cancelAndJoin()

        try{
            codec?.stop()
            codec?.release()
            inputSurface?.release()
        } catch (e: Exception){
            Log.e(LOG_TAG, "Error tearing down encoder", e)
        } finally {
            codec = null
            inputSurface = null
            Log.i(LOG_TAG, "H.264 hardware encoder stopped")
        }
    }
}